### ISSUE TITLE
Can't use serializer with `expect.addSnapshotSerializer`

### ISSUE THREAD

**Issue by MichaelDeBoey** [ikatyang/jest-snapshot-serializer-raw#64]
As can be seen in [this CodeSandbox](https://codesandbox.io/s/jest-snapshot-serializer-rawbug-nm6yp?file=/jest.setup.ts), it's not possible to use the serializer with `expect.addSnapshotSerializer`

![](https://user-images.githubusercontent.com/6643991/114326311-73e62780-9b34-11eb-89a9-ee70c5b662f0.png)

If we delete the `wrap` function (this would be a breaking change) and keep the plugin as simple as the following snippet

```ts
export const print = (val: unknown) => (val as string).trim();

export const test = (val: any) => typeof val === 'string';
```

It would be possible to use the serializer with `expect.addSnapshotSerializer`, in the `snapshotSerializers` config **and** without needing to use the `wrap` function in each test

@ikatyang I'm happy to create a PR if you want me to get this done.

**Comment by ikatyang** [comment]
It seems you forgot to use the namespace import, i.e., `import * as rawSerializer from "jest-snapshot-serializer-raw";`.

As for the `wrap` stuff, it's used for marking the content that we want to use the raw serializer. The snapshot would looks ambiguous if there is no such quote in certain cases, object values for example:

```js
// Jest Snapshot v1, https://goo.gl/fbAQLP

exports[`example snapshot 1`] = `
Object {
  "a": first line
second line,
  "b": first line
second line,
}
`;
```

**Comment by MichaelDeBoey** [comment]
> It seems you forgot to use the namespace import, i.e., `import * as rawSerializer from "jest-snapshot-serializer-raw";`.

That indeed removes the error, as you can see in [this CodeSandbox](https://codesandbox.io/s/jest-snapshot-serializer-rawbug-forked-8o5hv?file=/jest.setup.ts).

> As for the `wrap` stuff, it's used for marking the content that we want to use the raw serializer.

Using the `wrap` function, I need to enable it specifically for all my tests, but if we would remove the `wrap` function and implement this serializer as I did above, we can do all of the following **without** ever needing to use the `wrap` function in **each** test:
- add it to `snapshotSerializers` config
- add `expect.addSnapshotSerializer(rawSerializer)` in the test file where we want to have all tests to be serialized
- add `expect.addSnapshotSerializer(rawSerializer)` to the specific tests which we want to be serialized

In the cases where I want to enable the serializer in complete files or on all my tests, it's an extra burden to add the `wrap` function every time imo.  
So that's why I'm proposing to change the API (we can't do this without a breaking change unfortunately), to make the lives of everyone that wants to do this better.

We're currently using our own version of this serializer (thanks to @kentcdodds for introducing it! 👊) in:
- [`@remark-embedder/core`](https://github.com/remark-embedder/core/blob/ee7b2f9480f16249ac7d4d0618e18e7d4db0fa3e/src/__tests__/index.ts#L7-L13): enabled for all tests in the file
- [`@remark-embedder/transformer-codesandbox`](https://github.com/remark-embedder/transformer-codesandbox/blob/0601e007957fbfb8dcae4a116248b9869f41bbbe/src/__tests__/index.ts#L7-L12): enabled for all tests in the file
- [`@remark-embedder/transformer-oembed`](https://github.com/remark-embedder/transformer-oembed/blob/4982aa4948c1c451b2218f8288580c17e84f422b/src/__tests__/index.ts#L11-L17): enabled for all tests in the file
- [`gatsby-remark-embedder`](https://github.com/MichaelDeBoey/gatsby-remark-embedder/blob/1d9524e77c2be86b44259c680f71d0aa791c82de/tests/setup-env.js#L1-L7): enabled for all tests in the project

**Comment by ikatyang** [comment]
I guess we can provide another entrypoint for the serializer without `wrap`, but I'm not sure how to name it, any idea? maybe `jest-snapshot-serializer-raw/without-wrap`?

**Comment by kentcdodds** [comment]
Sounds fine to me

**Comment by j-f1** [comment]
`/always`?

**Comment by kentcdodds** [comment]
Personally it doesn't make much of a difference to me 😅

**Comment by kentcdodds** [comment]
Thanks!

**Comment by MichaelDeBoey** [comment]
Thanks for implementing this @ikatyang! 👊
